In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset = pd.read_csv('C:\cern data/DoubleMuRun2011A.csv')
dataset.head()

,Run,Event,Type1,E1,px1,py1,pz1,pt1,eta1,phi1,...,Type2,E2,px2,py2,pz2,pt2,eta2,phi2,Q2,M
0,165617,74601703,G,9.69873,-9.510430,0.366205,1.86329,9.51748,0.194546,3.10311,...,G,9.76332,7.327710,-1.152370,6.34728,7.41776,0.775564,-0.155984,1,17.49220
1,165617,75100943,G,6.20385,-4.266610,0.456545,-4.47930,4.29097,-0.912070,3.03499,...,G,9.66898,7.273970,-2.821120,-5.71040,7.80188,-0.678625,-0.369977,1,11.55340
2,165617,75587682,G,19.28920,-4.212080,-0.651623,18.81210,4.26219,2.190460,-2.98811,...,G,9.82439,4.343940,-0.473505,8.79849,4.36967,1.449670,-0.108575,1,9.16361
3,165617,75660978,G,7.04268,-6.326780,-0.268545,3.08025,6.33248,0.469033,-3.09917,...,G,5.58571,4.474760,0.848935,-3.23185,4.55458,-0.660499,0.187488,1,12.47740
4,165617,75947690,G,7.27507,0.102966,-5.533080,-4.72122,5.53403,-0.773616,-1.55219,...,G,7.31811,-0.398831,6.940810,2.28247,6.95226,0.322677,1.628190,1,14.31590

In [6]:
E = np.sqrt((dataset.px1**2 + dataset.py1**2 + dataset.pz1**2) + 105.7 *10**(-3))

In [4]:
print (pt1)

0          9.698156
1          6.202945
2         19.288892
3          7.041889
4          7.274304
5         14.941822
6         41.953700
7         14.430026
8          9.757758
9         10.161714
10         9.635937
11        12.507354
12        14.527051
13         6.010251
14        26.415735
15        12.071843
16         6.222748
17        18.240633
18        31.270206
19        44.224640
20        21.433620
21        59.922518
22        14.900090
23         9.107412
24         6.340534
25         5.174079
26        17.618636
27        15.003438
28        19.120772
29        13.370873
            ...
475435    26.058954
475436    11.868747
475437    10.945755
475438    56.457400
475439     6.400801
475440    14.002688
475441    17.662445
475442     7.762621
475443     6.378718
475444    82.584193
475445     7.477771
475446    16.120064
475447    11.330870
475448    16.947262
475449    12.347973
475450     7.094920
475451    14.277672
475452    30.433069
475453    14.512323
475454    11.380431
475455    15.501068
475456    13.000932
475457    15.261226
475458    38.705399
475459    27.157921
475460    21.674325
475461    27.264166
475462    18.460369
475463    38.866840
475464    21.726070
Length: 475465, dtype: float64

In [7]:
print (E)

0          9.703604
1          6.211459
2         19.291631
3          7.049390
4          7.281565
5         14.945359
6         41.954960
7         14.433688
8          9.763173
9         10.166913
10         9.641420
11        12.511579
12        14.530689
13         6.019038
14        26.417736
15        12.076220
16         6.231235
17        18.243530
18        31.271896
19        44.225836
20        21.436085
21        59.923400
22        14.903636
23         9.113213
24         6.348864
25         5.184284
26        17.621636
27        15.006961
28        19.123536
29        13.374825
            ...
475435    26.060982
475436    11.873199
475437    10.950582
475438    56.458336
475439     6.409053
475440    14.006462
475441    17.665437
475442     7.769426
475443     6.386998
475444    82.584833
475445     7.484836
475446    16.123342
475447    11.335533
475448    16.950380
475449    12.352252
475450     7.102365
475451    14.281374
475452    30.434806
475453    14.515965
475454    11.385074
475455    15.504477
475456    13.004997
475457    15.264689
475458    38.706764
475459    27.159867
475460    21.676763
475461    27.266105
475462    18.463232
475463    38.868200
475464    21.728503
Length: 475465, dtype: float64